# Use Node.js LTS
FROM node:20-slim

# Setup working directory
WORKDIR /app

# Install dumb-init strictly to handle PID 1 signals (like Ctrl+C SIGINT)
RUN apt-get update && apt-get install -y dumb-init --no-install-recommends && rm -rf /var/lib/apt/lists/*

# Copy package files strictly for layer caching
COPY package*.json ./

ARG NPM_TOKEN

RUN printf "registry=http://nexus.devopops.com/repository/npm-hosted/\n\
always-auth=true\n\
//nexus.devopops.com/repository/npm-hosted/:_authToken=%s\n" \
"$NPM_TOKEN" > /root/.npmrc

# Install production dependencies
RUN npm ci

# Copy all source files
COPY . .

# Expose server port
EXPOSE 3000

# Use dumb-init to orchestrate processes
ENTRYPOINT ["dumb-init", "--"]

# Run the app
CMD ["node", "app.js"]